#!/bin/zsh

path+=/usr/local/bin

typeset -a files
files=( /var/log/maillog(N) /var/log/mail.log(N) )

typeset opt
while getopts :a opt; do
    case $opt in
        (a) files=( /var/log/maillog*(OmN) /var/log/mail.log*(OmN) ) ;;
        (*) break ;;
    esac
done
shift $(( OPTIND - 1 ))

for f in $files; do
    case $f:t in
        (*.bz2) bzcat $f ;;
        (*.gz)  zcat $f  ;;
        (*)     cat $f ;;
    esac
done | pfanalyze -p | pfbydomain "$@"
