.\" Process this file with
.\" groff -man -Tascii pfqut.1
.\"
.TH PFQUT 1 "pfqut"
.
.SH NAME
.
pfqut \- Postfix queue utility
.
.\" -----------------------------------------------------------------
.
.SH SYNOPSIS
.
.B pfqut
.I COMMAND
[
.IR ARG \.\.\.\&
]
.
.SH DESCRIPTION
.
.TP
\fBpfqut list\fP [ \fB-QHA\fP ] [ \fIQID\fP ... ]
List all (or specified) messages in the queue.  Option
.B -Q
limits this to queued (i.e., deferred) messages;
.B -H
limits to held messages and 
.B -A
limits to active messages.  These options may be combined.
.
.TP
\fBpfqut get\fP [ \fB-ehb\fP ] \fIQID\fP \.\.\.
Print the envelope, header, and/or body of one or more messages in the queue.
.P
The envelope is printed in the format
.B FROM
.I SENDER
.B TO
.I RECIPIENT
[
.I RECIPIENT
] \.\.\.\&
.P
If no option is specified, the header and body are printed.
.
.TP
\fBpfqut release\fP [ \fB-a\fP | \fIQID\fP \.\.\. ]
Release one or more held messages.  Option \fB-a\fP causes all held messages to be released.
.
.TP
\fBpfqut delete\fP [ \fB-a\fP | \fIQID\fP \.\.\. ]
Delete one or more messages from the queue.  Option \fB-a\fP causes all messages in the queue to be deleted.
\fBUSE THIS COMMAND WITH CAUTION!\fP
.
.\" -----------------------------------------------------------------
.
.SH VERSION 
__VERSION__
.
.SH AUTHOR
__AUTHOR__
.
.SH COPYRIGHT
__COPYRIGHT__
.P
Released under the terms of the GNU
General Public License, version 2 -- see the file LICENSE for details.
